---
apiVersion: v2
name: research-mcp
description: Helm chart for research-mcp service
type: application
version: 0.1.1
appVersion: "0.1.0"
icon: https://raw.githubusercontent.com/IAmJonoBo/StratMaster/main/docs/assets/icon-research.png
