---
replicaCount: 1

image:
  repository: research-mcp
  tag: "0.1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

resources:
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 256Mi

automountServiceAccountToken: false
