[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "router-mcp"
version = "0.1.0"
description = "Model router MCP server"
requires-python = ">=3.13"
authors = [{ name = "StratMaster" }]
dependencies = [
  "fastapi>=0.117.1",
  "uvicorn[standard]>=0.36.0",
  "pydantic>=2.11.9",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
