# Grafana Configuration for StratMaster Production Telemetry Dashboard
# Phase 2 Implementation - Production telemetry dashboard with Grafana integration

grafana:
  enabled: true
  version: "10.4.0"
  
  # Admin configuration
  admin:
    user: "admin"
    # password should be set via environment variable GRAFANA_ADMIN_PASSWORD
    
  # Data sources configuration
  datasources:
    - name: "StratMaster Metrics"
      type: "prometheus"
      url: "http://prometheus:9090"
      access: "proxy"
      isDefault: true
      
    - name: "StratMaster Traces"
      type: "tempo"
      url: "http://tempo:3200"
      access: "proxy"
      
    - name: "StratMaster Logs"
      type: "loki"
      url: "http://loki:3100"
      access: "proxy"

  # Dashboard provisioning
  dashboards:
    - name: "DSPy Telemetry"
      path: "/var/lib/grafana/dashboards/dspy-telemetry.json"
      
    - name: "Constitutional Compliance"
      path: "/var/lib/grafana/dashboards/constitutional-compliance.json"
      
    - name: "Verification Pipeline"
      path: "/var/lib/grafana/dashboards/verification-pipeline.json"
      
    - name: "MCP Server Performance"
      path: "/var/lib/grafana/dashboards/mcp-performance.json"

  # Alerting configuration
  alerts:
    enabled: true
    notification_channels:
      - name: "slack-alerts"
        type: "slack"
        settings:
          url: "${SLACK_WEBHOOK_URL}"
          channel: "#stratmaster-alerts"
          
    rules:
      - alert: "HighConstitutionalViolationRate"
        condition: "constitutional_violations_rate > 0.1"
        for: "5m"
        message: "Constitutional violation rate above 10% for 5 minutes"
        
      - alert: "DSPyCompilationFailures"
        condition: "dspy_compilation_failure_rate > 0.05"
        for: "2m"
        message: "DSPy compilation failure rate above 5%"
        
      - alert: "MCPServerDown"
        condition: "up{job=\"mcp-servers\"} == 0"
        for: "1m"
        message: "MCP Server is down"

# Metrics collection configuration
metrics:
  collection_interval: "15s"
  retention: "30d"
  
  # Custom metrics
  custom_metrics:
    - name: "constitutional_violations_total"
      type: "counter"
      help: "Total number of constitutional violations detected"
      labels: ["severity", "principle", "service"]
      
    - name: "dspy_compilation_duration_seconds"
      type: "histogram"
      help: "Time taken for DSPy program compilation"
      labels: ["program_type", "success"]
      buckets: [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
      
    - name: "verification_questions_generated_total"
      type: "counter"
      help: "Total verification questions generated by CoVe"
      labels: ["question_type", "confidence_level"]
      
    - name: "debate_outcomes_total"
      type: "counter"
      help: "Total debate outcomes"
      labels: ["outcome", "constitutional_compliant"]