[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stratmaster-dsp"
version = "0.1.0"
description = "DSPy program stubs for StratMaster"
requires-python = ">=3.13"
authors = [{ name = "StratMaster" }]
dependencies = [
  "pydantic>=2.11.9",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
