[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stratmaster-integrations"
version = "0.1.0"
description = "StratMaster integrations package"
requires-python = ">=3.11"
authors = [{ name = "StratMaster" }]
dependencies = [
    "httpx>=0.25.0",
    "tenacity>=8.0.0",
    "python-multipart>=0.0.6",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
