[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stratmaster-research"
version = "0.1.0"
description = "StratMaster research package"
requires-python = ">=3.11"
authors = [{ name = "StratMaster" }]
dependencies = []

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
