[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "compression-mcp"
version = "0.1.0"
description = "LLMLingua compression MCP server"
requires-python = ">=3.11"
authors = [{ name = "StratMaster" }]
dependencies = ["fastapi>=0.117.1", "uvicorn[standard]>=0.36.0"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
