[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "knowledge"
version = "0.1.0"
description = "Knowledge fabric storage and GraphRAG materialisation"
requires-python = ">=3.11"
authors = [{ name = "StratMaster" }]
dependencies = [
  "pydantic>=2.11.0",
  "PyYAML>=6.0",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
