apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stratmaster-api.fullname" . }}-expertise-mcp
  labels:
    {{- include "stratmaster-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: expertise-mcp
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stratmaster-api.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: expertise-mcp
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "stratmaster-api.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: expertise-mcp
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stratmaster-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: expertise-mcp
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.expertiseMcp.image.repository }}:{{ .Values.expertiseMcp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.expertiseMcp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: EXPERTISE_MCP_LOG_LEVEL
              value: {{ .Values.expertiseMcp.logLevel | default "info" | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.expertiseMcp.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/configs
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "stratmaster-api.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}