{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "stratmaster-api.fullname" . }}-expertise-mcp
  labels:
    {{- include "stratmaster-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: expertise-mcp
spec:
  podSelector:
    matchLabels:
      {{- include "stratmaster-api.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: expertise-mcp
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "stratmaster-api.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: api
    - podSelector:
        matchLabels:
          {{- include "stratmaster-api.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: orchestrator
    ports:
    - protocol: TCP
      port: 8080
  egress:
  # Deny all external egress by default - expertise-mcp should be local-only
  - to: []
    ports: []
{{- end }}