[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "knowledge-mcp"
version = "0.1.0"
description = "Knowledge MCP server"
requires-python = ">=3.11"
authors = [{ name = "StratMaster" }]
dependencies = [
  "fastapi>=0.117.1",
  "uvicorn[standard]>=0.36.2",
  "pydantic>=2.11.9",
  "httpx>=0.28.1",
  "qdrant-client>=1.14.4",
  "sentence-transformers>=3.4.4",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
