# Real-time Collaboration on Debate Outcomes Configuration
# Phase 2 Implementation - Real-time collaborative debate resolution

# WebSocket configuration for real-time communication
websocket:
  enabled: true
  port: 8084
  path: "/ws/collaboration"
  
  # Connection management
  connection:
    max_connections_per_session: 10
    heartbeat_interval: "30s"
    connection_timeout: "5m"
    reconnect_attempts: 3
    
  # Message types
  message_types:
    - "debate_update"
    - "constitutional_violation"
    - "expert_comment"
    - "user_vote"
    - "resolution_proposal"
    - "consensus_reached"
    - "session_status"

# Collaborative session management
sessions:
  # Session lifecycle
  lifecycle:
    max_duration: "2h"
    idle_timeout: "30m"
    auto_save_interval: "5m"
    
  # Session types
  types:
    - name: "constitutional_review"
      description: "Review constitutional violations in debate outcomes"
      min_participants: 2
      max_participants: 8
      required_roles: ["constitutional_expert", "debate_moderator"]
      
    - name: "expert_consensus"
      description: "Expert panel consensus on complex recommendations"
      min_participants: 3
      max_participants: 12
      required_roles: ["domain_expert", "methodology_expert"]
      
    - name: "stakeholder_review"
      description: "Stakeholder review of strategic recommendations"
      min_participants: 2
      max_participants: 20
      required_roles: ["stakeholder", "strategy_expert"]

# Participant roles and permissions
roles:
  # Constitutional expert role
  - name: "constitutional_expert"
    permissions:
      - "view_violations"
      - "propose_amendments"
      - "vote_on_resolutions"
      - "escalate_violations"
      - "access_violation_history"
      
  # Domain expert role
  - name: "domain_expert"
    permissions:
      - "comment_on_recommendations"
      - "suggest_evidence"
      - "vote_on_accuracy" 
      - "propose_alternatives"
      - "access_research_context"
      
  # Debate moderator role
  - name: "debate_moderator"
    permissions:
      - "manage_session"
      - "moderate_discussions"
      - "call_for_votes"
      - "declare_consensus"
      - "access_all_data"
      
  # Stakeholder role
  - name: "stakeholder"
    permissions:
      - "view_outcomes"
      - "provide_feedback"
      - "vote_on_acceptability"
      - "request_clarifications"
      
  # Strategy expert role
  - name: "strategy_expert"
    permissions:
      - "review_strategic_coherence"
      - "assess_implementation_feasibility" 
      - "propose_refinements"
      - "validate_assumptions"

# Real-time features
real_time_features:
  # Live debate tracking
  live_tracking:
    enabled: true
    features:
      - "argument_progress"
      - "constitutional_compliance_status"
      - "expert_consensus_meter"
      - "evidence_strength_indicators"
      - "violation_alerts"
      
  # Collaborative editing
  collaborative_editing:
    enabled: true
    conflict_resolution: "operational_transform"
    auto_merge: true
    change_tracking: true
    
  # Real-time voting
  voting:
    enabled: true
    voting_methods:
      - "simple_majority"
      - "qualified_majority" 
      - "consensus"
      - "weighted_expert_vote"
    vote_visibility: "anonymous_until_complete"
    
  # Live notifications
  notifications:
    enabled: true
    types:
      - "new_violation_detected"
      - "expert_joined_session"
      - "consensus_threshold_reached"
      - "voting_started"
      - "session_ending_soon"

# Consensus mechanisms
consensus:
  # Consensus algorithms
  algorithms:
    - name: "expert_weighted"
      description: "Votes weighted by domain expertise"
      weight_factors:
        - "domain_knowledge_score"
        - "track_record"
        - "certification_level"
        
    - name: "stakeholder_democratic"
      description: "Equal weight democratic voting"
      threshold: 0.6
      
    - name: "constitutional_strict"
      description: "Unanimous agreement required for constitutional matters"
      threshold: 1.0
      timeout: "45m"
      
  # Consensus tracking
  tracking:
    enabled: true
    metrics:
      - "participation_rate"
      - "time_to_consensus"
      - "number_of_iterations"
      - "dissent_reasons"
      - "amendment_acceptance_rate"

# Integration with debate system
debate_integration:
  # Automatic session creation
  auto_session_triggers:
    - condition: "constitutional_violations_detected"
      session_type: "constitutional_review"
      priority: "high"
      
    - condition: "expert_consensus_required"
      session_type: "expert_consensus"
      priority: "medium"
      
    - condition: "stakeholder_approval_needed"
      session_type: "stakeholder_review"
      priority: "low"
      
  # Outcome synchronization
  outcome_sync:
    enabled: true
    sync_frequency: "real_time"
    conflict_resolution: "collaborative_session_wins"
    
  # Historical analysis
  historical_tracking:
    enabled: true
    retention_period: "2y"
    analytics:
      - "session_effectiveness"
      - "expert_contribution_patterns"
      - "consensus_time_trends"
      - "violation_resolution_success"

# Quality assurance
quality_assurance:
  # Session quality metrics
  metrics:
    - "participant_engagement_score"
    - "decision_quality_rating"
    - "process_adherence_score"
    - "outcome_implementation_success"
    
  # Automated quality checks
  automated_checks:
    - "minimum_participation_threshold"
    - "expertise_coverage_validation"
    - "bias_detection_in_discussions"
    - "evidence_sufficiency_check"
    
  # Post-session analysis
  post_session:
    enabled: true
    analysis_types:
      - "participant_feedback_analysis"
      - "decision_outcome_tracking"
      - "process_improvement_suggestions"
      - "expert_performance_assessment"

# Security and privacy
security:
  # Session security
  session_security:
    encryption: "end_to_end"
    authentication_required: true
    session_isolation: true
    audit_logging: "comprehensive"
    
  # Data privacy
  privacy:
    participant_anonymity: "configurable"
    data_retention: "session_based"
    gdpr_compliance: true
    consent_tracking: true
    
  # Access control
  access_control:
    role_based: true
    session_based_permissions: true
    ip_whitelisting: "optional"
    multi_factor_auth: "recommended"