[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bge-reranker"
version = "0.1.0"
description = "BGE reranker utilities"
requires-python = ">=3.11"
authors = [{ name = "StratMaster" }]
dependencies = ["pydantic>=2.11.0", "typer>=0.12.5"]

[project.scripts]
bge-rerank = "bge_reranker.cli:app"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
test-cli = ["pytest>=8.0.0", "typer>=0.12.5"]
