apiVersion: apps/v1
kind: Deployment
metadata:
  name: stratmaster-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stratmaster-api
  template:
    metadata:
      labels:
        app: stratmaster-api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          args: ["uvicorn", "stratmaster_api.app:create_app", "--factory", "--host", "0.0.0.0", "--port", "8080"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 256Mi
            limits:
              memory: 256Mi
