enabled: true
target_token_ratio: 0.5
safety_keywords:
  - password
  - secret
  - key
domains_exempt:
  - provenance
  - numeric_results
# TODO[COMP-501]: Tune task-specific parameters, wire into eval harness, and document guardrails (see `docs/backlog.md#todo-comp-501-llmlingua-parameter-tuning`).
