---
enabled: true
default_profile: general
profiles:
  general:
    target_token_ratio: 0.5
    max_tokens: 2048
    preserve_headings: true
    ensure_bullets: true
  research_brief:
    target_token_ratio: 0.4
    max_tokens: 1024
    highlight_citations: true
    allow_structured_tables: false
  agent_memory:
    target_token_ratio: 0.35
    max_tokens: 800
    redact_pii: true
    collapse_reasoning: true
safety_keywords:
  - password
  - secret
  - key
  - credential
  - ssn
domains_exempt:
  - provenance
  - numeric_results
  - legal_disclaimer
guardrails:
  refuse_on_keywords: true
  preserve_sections:
    - "Provenance"
    - "Decisions"
  min_ratio: 0.3
  max_ratio: 0.6
evaluation:
  dataset: configs/eval/compression/llmlingua-dataset.yaml
  metrics:
    - name: rougeL
      threshold: 0.78
    - name: factual_consistency
      threshold: 0.95
  regression_suite:
    command: python -m compression.eval.llmlingua --config configs/eval/compression/llmlingua.yaml
