[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stratmaster-api"
version = "0.1.0"
description = "StratMaster FastAPI service"
requires-python = ">=3.11"
authors = [{ name = "StratMaster" }]
dependencies = [
  "fastapi>=0.117.1",
  "uvicorn[standard]>=0.30.0",
  "pydantic>=2.5.0",
  "httpx>=0.25.0",
  "PyYAML>=6.0.2",
  "langgraph>=0.2.0",
  "redis>=5.0.0",
  "prometheus-client>=0.20.0",
  "opentelemetry-api>=1.27.0",
  "opentelemetry-sdk>=1.27.0",
  "opentelemetry-exporter-prometheus>=0.46b0",
  "opentelemetry-instrumentation-fastapi>=0.48b0",
  "scikit-learn>=1.3.0",
  "python-multipart>=0.0.6",
  "tenacity>=8.0.0",
  "python-keycloak>=3.7.0",
  "python-jose[cryptography]>=3.3.0",
  "passlib[bcrypt]>=1.7.4",
  "cryptography>=41.0.0",
  "presidio-analyzer>=2.2.33",
  "presidio-anonymizer>=2.2.33",
  "structlog>=23.0.0"
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
