[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stratmaster-api"
version = "0.1.0"
description = "StratMaster FastAPI service"
requires-python = ">=3.11"
authors = [{ name = "StratMaster" }]
dependencies = [
  "fastapi>=0.117.1",
  "uvicorn[standard]>=0.30.0",
  "pydantic>=2.5.0",
  "httpx>=0.25.0",
  "PyYAML>=6.0.2",
  "langgraph>=0.2.0",
  "redis>=5.0.0",
  "prometheus-client>=0.20.0",
  "opentelemetry-api>=1.27.0",
  "opentelemetry-sdk>=1.27.0",
  "opentelemetry-exporter-prometheus>=1.12.0",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
