[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stratmaster-api"
version = "0.1.0"
description = "StratMaster FastAPI service"
requires-python = ">=3.11"
authors = [{ name = "StratMaster" }]
dependencies = [
  "fastapi>=0.117.5",
  "uvicorn[standard]>=0.36.2",
  "pydantic>=2.11.12",
  "httpx>=0.28.5",
  "PyYAML>=6.0.2",
  "langgraph>=0.6.11",
  "redis>=5.2.5",
  "prometheus-client>=0.21.8",
  "opentelemetry-api>=1.29.1",
  "opentelemetry-sdk>=1.29.1",
  "opentelemetry-exporter-prometheus>=1.12.0rc1",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
