[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stratmaster-api"
version = "0.1.0"
description = "StratMaster FastAPI service"
requires-python = ">=3.11"
authors = [{ name = "StratMaster" }]
dependencies = [
  "fastapi>=0.117.1",
  "uvicorn[standard]>=0.36.0",
  "pydantic>=2.11.9",
  "httpx>=0.28.1",
  "PyYAML>=6.0",
  "langgraph>=0.6.7",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
