[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "retrieval-splade"
version = "0.1.0"
description = "SPLADE expansion and indexing utilities"
requires-python = ">=3.13"
authors = [{ name = "StratMaster" }]
dependencies = ["pydantic>=2.11.0", "typer>=0.12.5", "PyYAML>=6.0"]

[project.scripts]
splade-expand = "splade.expand:app"
splade-index = "splade.index:app"
splade-verify = "splade.verify:app"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
test-cli = ["pytest>=8.0.0", "typer>=0.12.5"]
