---
# SealedSecret template for StratMaster production secrets
# Encrypted secrets that can be stored in Git and applied to cluster
# Use: kubeseal < production-secrets.yaml > sealed-production-secrets.yaml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: stratmaster-production
  labels:
    app.kubernetes.io/name: stratmaster
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: stratmaster-platform
spec:
  encryptedData:
    # These will be populated by kubeseal command
    # Example format (actual values will be much longer):
    postgres-host: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
    postgres-port: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
    postgres-database: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
    postgres-username: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
    postgres-password: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
    postgres-url: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
  template:
    metadata:
      name: postgres-credentials
      namespace: stratmaster-production
      labels:
        app.kubernetes.io/name: stratmaster
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: stratmaster-platform
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secrets
  namespace: stratmaster-production
  labels:
    app.kubernetes.io/name: stratmaster
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: stratmaster-platform
spec:
  encryptedData:
    jwt-secret: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
    session-secret: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
    encryption-key: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
  template:
    metadata:
      name: jwt-secrets
      namespace: stratmaster-production
      labels:
        app.kubernetes.io/name: stratmaster
        app.kubernetes.io/component: auth
        app.kubernetes.io/part-of: stratmaster-platform
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-api-keys
  namespace: stratmaster-production
  labels:
    app.kubernetes.io/name: stratmaster
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: stratmaster-platform
spec:
  encryptedData:
    openai-api-key: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
    anthropic-api-key: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
    langfuse-public-key: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
    langfuse-secret-key: "AgBy3i4OJSWK+PiTySYZZA9rO43cGHuSmhkmQqkuyWQxr..."
  template:
    metadata:
      name: external-api-keys
      namespace: stratmaster-production
      labels:
        app.kubernetes.io/name: stratmaster
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: stratmaster-platform
    type: Opaque