site_name: StratMaster Documentation
site_description: Comprehensive documentation for the AI-powered Brand Strategy platform
site_url: https://iamjonobo.github.io/StratMaster/
repo_url: https://github.com/IAmJonoBo/StratMaster
repo_name: IAmJonoBo/StratMaster

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.tabs.link
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes

nav:
  - Home: index.md
  - Tutorials:
    - tutorials/index.md
    - Quick Start: tutorials/quickstart.md
    - Your First Analysis: tutorials/first-analysis.md
  - How-to Guides:
    - how-to/index.md
    - Development Setup: how-to/development-setup.md
    - Deployment Guide: how-to/deployment.md
    - Infrastructure Setup: how-to/infrastructure.md
    - Operations Guide: how-to/operations-guide.md
    - Troubleshooting: how-to/troubleshooting.md
    - FAQ: how-to/faq.md
  - Reference:
    - reference/index.md
    - API Reference:
      - reference/api/index.md
      - Gateway API: reference/api/gateway.md
      - Research MCP: reference/api/research-mcp.md
      - Knowledge MCP: reference/api/knowledge-mcp.md
      - Router MCP: reference/api/router-mcp.md
      - OpenAPI Spec: reference/api/openapi.md
    - CLI Reference:
      - reference/cli/index.md
      - Make Commands: reference/cli/make-commands.md
      - Scripts: reference/cli/scripts.md
    - Configuration:
      - reference/configuration/index.md
      - Environment Variables: reference/configuration/environment.md
      - YAML Configs: reference/configuration/yaml-configs.md
  - Explanation:
    - explanation/index.md
    - Architecture Overview: explanation/architecture.md
    - Multi-Agent Debate: explanation/multi-agent-debate.md
    - Security Model: explanation/security.md
    - Design Decisions: explanation/design-decisions.md

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/IAmJonoBo/StratMaster
      name: GitHub Repository