apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stratmaster-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: stratmaster
  source:
    repoURL: https://github.com/IAmJonoBo/StratMaster
    targetRevision: develop
    path: helm
    helm:
      valueFiles:
        - values-staging.yaml
      parameters:
        - name: image.tag
          value: staging-${ARGOCD_APP_REVISION}
        - name: global.environment
          value: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: stratmaster-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 5