apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stratmaster-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: stratmaster
  source:
    repoURL: https://github.com/IAmJonoBo/StratMaster
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values-production.yaml
      parameters:
        - name: image.tag
          value: ${ARGOCD_APP_REVISION}
        - name: global.environment
          value: production
  destination:
    server: https://kubernetes.default.svc
    namespace: stratmaster-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Secret
      jsonPointers:
        - /data