[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stratmaster-collaboration"
version = "0.1.0"
description = "Real-time collaboration service for StratMaster debate outcomes"
requires-python = ">=3.11"
authors = [{ name = "StratMaster" }]
dependencies = [
  "fastapi>=0.117.5",
  "uvicorn[standard]>=0.36.2",
  "websockets>=13.3",
  "redis>=5.2.5",
  "pydantic>=2.11.12",
  "python-socketio>=5.13.0",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

