[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stratmaster-orchestration-os"
version = "0.1.0"
description = "Adaptive orchestration and decision OS tooling for StratMaster"
requires-python = ">=3.11"
authors = [{ name = "StratMaster" }]
dependencies = ["pyyaml>=6.0.2"]

[project.scripts]
strat-orchestrate = "orchestration_os.cli:app_main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
