replicaCount: 1

image:
  repository: ghcr.io/your-org/stratmaster
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: stratmaster.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

otel:
  enabled: true
  endpoint: http://otel-collector:4317

opa:
  enabled: true

langfuse:
  enabled: false

secrets:
  enabled: false
  items: [] # list of {name, key, valueFrom}
