# ColBERT retrieval config
corpus:
  path: seeds/demo-ceps-jtbd-dbas.json
  text_fields:
    - summary
    - title
index:
  name: colbert-default
  shards: 1
  replication: 1
collection:
  name: documents
embedding:
  model: colbert-ir/colbertv2.0
  dim: 128
  max_document_length: 512
search:
  k: 50
  max_passages: 4
  # used in hybrid mode
  alpha_dense_sparse_mix: 0.7
storage:
  backend: opensearch
  opensearch:
    host: http://opensearch:9200
    index_prefix: colbert_
  output_dir: artifacts/colbert
telemetry:
  enabled: true
  otlp_endpoint: http://otel-collector:4317
