dense:
  model: bge-base-en-v1.5
  k: 50
sparse:
  method: bm25
  # missing required 'k' field to trigger validation error
alpha: "not-a-float"
reranker:
  model_name: bge-reranker-large
  topk_in: 100
  topk_out: 20
