[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stratmaster-strategy"
version = "0.1.0"
description = "StratMaster Strategy Engine - Document processing and strategy synthesis"
authors = [{name = "StratMaster Team"}]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "pydantic>=2.5.0",
    "python-docx>=0.8.11",
    "PyPDF2>=3.0.0",
    "python-pptx>=0.6.21",
    "markdown>=3.5.0",
    "spacy>=3.7.0",
    "nltk>=3.8.0",
    "scikit-learn>=1.3.0",
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "jinja2>=3.1.0",
    "typer>=0.9.0",
    "rich>=13.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "mypy>=1.5.0",
]

[project.scripts]
strategy-pipeline = "strategy_pipeline.cli:app"

[tool.hatch.build.targets.wheel]
packages = ["src/strategy_pipeline"]

[tool.black]
line-length = 88
target-version = ['py311']

