---
name: Trunk Lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install packages for type checking
        run: |
          python -m pip install --upgrade pip
          pip install -e packages/api -e packages/mcp-servers/research-mcp

      - name: Run Trunk check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
