---
name: Trunk Lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Trunk
        uses: trunk-io/trunk-action@v1

      - name: Install packages for type checking
        run: |
          python -m pip install --upgrade pip
          # Install only the API package which is known to work reliably
          pip install -e packages/api
          # Try to install research-mcp with timeout, skip if it fails due to network issues
          timeout 180 pip install -e packages/mcp-servers/research-mcp || echo "Research MCP installation timed out - skipping for type checking"

      - name: Run Trunk check
        run: |
          trunk --version
          trunk init --ci || true
          trunk check --all --no-fix
