name: Validate Milestones

on:
  push:
    branches: [ v2, main ]
  pull_request:
    branches: [ v2, main ]
  workflow_dispatch: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install gh (CLI is pre-installed on ubuntu, ensure authless works)
        run: gh --version || true
      - name: Run milestone validator
        run: |
          python scripts/validate_milestones.py --verbose
