name: Validate Issues Source

on:
  push:
    paths:
      - 'ISSUES.md'
      - 'issue_suite.config.yaml'
      - '.github/workflows/validate-issues.yml'
  pull_request:
    paths:
      - 'ISSUES.md'
      - 'issue_suite.config.yaml'
      - '.github/workflows/validate-issues.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
            python-version: '3.13'

      - name: Install IssueSuite (minimal)
        run: |
          python -m pip install --upgrade pip
          if pip install 'issuesuite>=0.1.4'; then
            echo 'IssueSuite installed from PyPI'
          else
            echo 'PyPI install failed; cloning source repo fallback'
            git clone --depth 1 https://github.com/IAmJonoBo/IssueSuite issuesuite_src
            (cd issuesuite_src && pip install .)
          fi

      - name: Verify gh CLI
        run: gh --version || (echo "gh CLI not found" && exit 1)

      - name: Auth GH (GITHUB_TOKEN)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth status || echo "gh will use GITHUB_TOKEN automatically"

      - name: Validate structure & IDs
        run: |
          issuesuite validate --config issue_suite.config.yaml --strict

      - name: Generate schemas (mock)
        env:
          ISSUES_SUITE_MOCK: '1'
        run: |
          issuesuite schema --config issue_suite.config.yaml

      - name: Dry-run sync (mock)
        env:
          ISSUES_SUITE_MOCK: '1'
        run: |
          issuesuite sync --dry-run --update --config issue_suite.config.yaml --summary-json issues_summary.json

      - name: Export parsed issues
        run: |
          issuesuite export --config issue_suite.config.yaml --output issues_export.json --pretty

      - name: Human-readable summary
        run: |
          issuesuite summary --config issue_suite.config.yaml > issues_summary.txt

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: issues-validation
          path: |
            issues_export.json
            issues_summary.json
            issues_summary.txt
            issue_export.schema.json
            issue_change_summary.schema.json

      - name: Completion Note
        if: always()
        run: echo "IssueSuite validation workflow complete" > validation_summary.txt
      - name: Upload completion note
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: issues-validation-summary
          path: validation_summary.txt
